"""initial_schema

Revision ID: 92e35f87fe57
Revises: 
Create Date: 2026-04-21 12:19:29.175138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92e35f87fe57'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('table_name', sa.String(length=50), nullable=False),
    sa.Column('record_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=10), nullable=False),
    sa.Column('changed_by', sa.Uuid(), nullable=True),
    sa.Column('changed_by_name', sa.String(length=255), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_changed_at'), 'audit_logs', ['changed_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_record_id'), 'audit_logs', ['record_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_table_name'), 'audit_logs', ['table_name'], unique=False)
    op.create_table('company_settings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('company_type', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('logo_url', sa.String(length=512), nullable=True),
    sa.Column('primary_color', sa.String(length=7), nullable=False),
    sa.Column('secondary_color', sa.String(length=7), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('investment_duration_months', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('investor_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investor_id'], ['investors.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('investments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('investor_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('initial_capital', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('current_value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], use_alter=True),
    sa.ForeignKeyConstraint(['investor_id'], ['investors.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investments_investor_id'), 'investments', ['investor_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('investor_id', sa.Uuid(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_by', sa.Uuid(), nullable=True),
    sa.Column('replied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reply_body', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['investor_id'], ['investors.id'], ),
    sa.ForeignKeyConstraint(['read_by'], ['users.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_investor_id'), 'messages', ['investor_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('investor_id', sa.Uuid(), nullable=False),
    sa.Column('investment_id', sa.Uuid(), nullable=True),
    sa.Column('report_type', sa.String(length=30), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('storage_path', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('generated_by', sa.Uuid(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signature_name', sa.String(length=255), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], use_alter=True),
    sa.ForeignKeyConstraint(['investment_id'], ['investments.id'], use_alter=True),
    sa.ForeignKeyConstraint(['investor_id'], ['investors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_available_at'), 'reports', ['available_at'], unique=False)
    op.create_index(op.f('ix_reports_investor_id'), 'reports', ['investor_id'], unique=False)
    op.create_table('webauthn_credentials',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('credential_id', sa.LargeBinary(), nullable=False),
    sa.Column('public_key', sa.LargeBinary(), nullable=False),
    sa.Column('sign_count', sa.BigInteger(), nullable=False),
    sa.Column('device_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credential_id')
    )
    op.create_index(op.f('ix_webauthn_credentials_user_id'), 'webauthn_credentials', ['user_id'], unique=False)
    op.create_table('performances',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('investment_id', sa.Uuid(), nullable=False),
    sa.Column('investor_id', sa.Uuid(), nullable=False),
    sa.Column('period_type', sa.String(length=10), nullable=False),
    sa.Column('period_label', sa.String(length=20), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('opening_value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('closing_value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('net_deposits', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('gross_gain', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('fees', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('roi_pct', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('max_drawdown_pct', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('calculated_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['calculated_by'], ['users.id'], use_alter=True),
    sa.ForeignKeyConstraint(['investment_id'], ['investments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['investor_id'], ['investors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('investment_id', 'period_type', 'period_label')
    )
    op.create_index(op.f('ix_performances_investment_id'), 'performances', ['investment_id'], unique=False)
    op.create_index(op.f('ix_performances_investor_id'), 'performances', ['investor_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('investment_id', sa.Uuid(), nullable=False),
    sa.Column('investor_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('confirmed_by', sa.Uuid(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], use_alter=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], use_alter=True),
    sa.ForeignKeyConstraint(['investment_id'], ['investments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['investor_id'], ['investors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_investment_id'), 'transactions', ['investment_id'], unique=False)
    op.create_index(op.f('ix_transactions_investor_id'), 'transactions', ['investor_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_investor_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_investment_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_performances_investor_id'), table_name='performances')
    op.drop_index(op.f('ix_performances_investment_id'), table_name='performances')
    op.drop_table('performances')
    op.drop_index(op.f('ix_webauthn_credentials_user_id'), table_name='webauthn_credentials')
    op.drop_table('webauthn_credentials')
    op.drop_index(op.f('ix_reports_available_at'), table_name='reports')
    op.drop_index(op.f('ix_reports_investor_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_messages_investor_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_investments_investor_id'), table_name='investments')
    op.drop_table('investments')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('investors')
    op.drop_table('company_settings')
    op.drop_index(op.f('ix_audit_logs_table_name'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_record_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_changed_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
